name: 'Run tfsec with sarif upload'
description: 'Run tfsec against terraform code base and upload the sarif output to the github repo'
author: 'Owen Rumney'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . ( root of the repository)
    default: '.'
outputs:
  tfsec-return-code:
    description: 'tfsec command return code'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'search'
  color: 'gray-dark'